### ISSUE TITLE
Models doesn't appears

### ISSUE THREAD

**Issue by CaptainYunak** [HydrusStudio/oppidium-assets#3]
Hi, 
I have a problem with tree's models (Models/Environnement/Tree), it does appear in the list but it does not appear on the scene, I can't use it. However for the fallen tree there is no problem.

Cordially,
CaptainYunak

**Comment by clavos** [comment]
Hi !

If it appear in the list of objects then it means that it has been created, so it should be a problem with the material or the texture of the Tree.prefab. Sometimes the .prefab doesn't link correctly to it's assets.

## Possible solution
Try to link manually the Tree.prefab to it's texture and material, the tree should appear !
What's your version of Unity ?

**Comment by CaptainYunak** [comment]
Your solution was the right one, the problem is solved
